name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build_sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: generate-sitemap
        uses: cicirello/generate-sitemap@v1.10.4

      - uses: stefanzweifel/git-auto-commit-action@v5
